default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV["PGPORT"] %>

development:
  <<: *default
  database: web_ruby_rails_ban_do_noi_that_mocphuong_development

test:
  <<: *default
  database: web_ruby_rails_ban_do_noi_that_mocphuong_test

production:
  url: <%= ENV["DATABASE_URL"] %>
